### ISSUE TITLE
Debug car control issue

### ISSUE THREAD

**Issue by FrancoisMasson1990** [commaai/openpilot-tools#11]
Can debug_control be used to send acceleration and brakes to the car through a joystick ?
I mean by that : is it possible to drive the car just by using a joystick ?

**Comment by rbiasini** [comment]
yes. out of the box, should work for every car where OP controls gas and brake (some car might require you to enable cruise in order to accept commands though).

**Comment by FrancoisMasson1990** [comment]
Also I m able to turn the steer with a joystick but the steer angle is limited in a very short range of angle (+-10 degrees ) I try to change the values in debug_controls.py ( actuators.steerAngle = axis_3  * values) but nothing change. Is there a link with SAFETY_ALLOUTPUT ? (Assuming I set the environment to MOCK) 
Also ECU Camera/DSU/APGS Simulated, are supposed  to be True when starting the car ?
