### ISSUE TITLE
model_path.poly

### ISSUE THREAD

**Issue by arslansarp** [commaai/openpilot-tools#21]
There is a problem in **ui.py** **if check in line 92**. There is no **poly** in the model structure. So it fails.

`('Model structure : ', <log.capnp:ModelData.PathData reader (points = [-0.0002432426, 0.00026844209, 0.0004326448, 0.0010469627, 0.001361216, 0.0020935291, 0.0016650213, 0.003136467, 0.0043678759, 0.005561382, 0.0065744263, 0.0083982022, 0.010051556, 0.012223821, 0.014295383, 0.01646249, 0.019140648, 0.022653025, 0.025600031, 0.029398577, 0.033503108, 0.0370774, 0.040271517, 0.043741047, 0.048098549, 0.052571185, 0.055899832, 0.060242135, 0.063961871, 0.068778165, 0.073815882, 0.078710929, 0.084540375, 0.090034135, 0.095038079, 0.10082614, 0.10694723, 0.11200286, 0.11830249, 0.12321176, 0.12881488, 0.13504936, 0.14175279, 0.14850761, 0.15486789, 0.16121906, 0.16859198, 0.17451309, 0.18120955, 0.18742912], prob = 1, std = 0.11217999)>)
Traceback (most recent call last):
  File "ui.py", line 589, in <module>
    ui_thread(args.ip_address, args.frame_address)
  File "ui.py", line 421, in ui_thread
    model_data = extract_model_data(md)
  File "ui.py", line 104, in extract_model_data
    cpath=ModelPoly(md.model.path),
  File "ui.py", line 92, in __init__
    if len(model_path.poly): #len(model_path.points):
  File "capnp/lib/capnp.pyx", line 1048, in capnp.lib.capnp._DynamicStructReader.__getattr__ (capnp/lib/capnp.cpp:22851)
  File "capnp/lib/capnp.pyx", line 1046, in capnp.lib.capnp._DynamicStructReader.__getattr__ (capnp/lib/capnp.cpp:22766)
  File "capnp/lib/capnp.pyx", line 1042, in capnp.lib.capnp._DynamicStructReader._get (capnp/lib/capnp.cpp:22632)

AttributeError: capnp/schema.c++:486: failed: struct has no such member; name = poly

stack: 0x7f01f7e82c18 0x7f01f7c88eec 0x7f01f7c3e595 0x4bc2f8 0x4b9b66 0x4d5669 0x4eef5e 0x4eeb66 0x4aaafb 0x4c166d 0x4c141f 0x4c141f 0x4b9b66 0x4eb69f 0x4e58f2 0x4e41a6 0x4938ce 0x7f02363ef830 0x493299
    ??:0: returning here
    ??:0: returning here
    ??:0: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:0: returning here
    ??:?: returning here
`

**Comment by pd0wm** [comment]
This should be fixed by using the latest openpilot version. You can reopen if you still have this issue

**Comment by arslansarp** [comment]
Still having the same issue after using latest openpilot version.

python tools/replay/ui.py 
/home/ipek/openpilot/selfdrive/services.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for k, v in yaml.load(f).items():
make: 'simple_kalman_impl.so' is up to date.
mkdir -p obj
ECU Camera Simulated: True
ECU DSU Simulated: True
ECU APGS Simulated: False
ECU Gas Interceptor: False
Traceback (most recent call last):
  File "tools/replay/ui.py", line 584, in <module>
    ui_thread(args.ip_address, args.frame_address)
  File "tools/replay/ui.py", line 416, in ui_thread
    model_data = extract_model_data(md)
  File "tools/replay/ui.py", line 104, in extract_model_data
    cpath=ModelPoly(md.model.path),
  File "tools/replay/ui.py", line 92, in __init__
    if len(model_path.poly):
  File "capnp/lib/capnp.pyx", line 1048, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1046, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1042, in capnp.lib.capnp._DynamicStructReader._get
AttributeError: capnp/schema.c++:486: **failed: struct has no such member; name = poly**
stack: 0x7fc70a229718 0x7fc70a03942b 0x7fc70a00f3a6 0x4bc2f8 0x4b9b66 0x4d5669 0x4eef5e 0x4eeb66 0x4aaafb 0x4c166d 0x4c141f 0x4c141f 0x4b9b66 0x4eb69f 0x4e58f2 0x4e41a6 0x4938ce 0x7fc731c68830 0x493299
    ??:0: returning here
    ??:0: returning here
    ??:0: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:0: returning here
