### ISSUE TITLE
Running joysticd.py issue

### ISSUE THREAD

**Issue by yangwoo-kim** [commaai/openpilot-tools#38]
Hello,
I'm trying to test the tools and stuck on the following:

`(openpilot) yangwoo@corolla:~/work/corolla/openpilot/tools$ python carcontrols/joystickd.py `
`pygame 1.9.6`
`Hello from the pygame community. https://www.pygame.org/contribute.html`
`Traceback (most recent call last):`
`  File "carcontrols/joystickd.py", line 11, in <module>`
`    import cereal.messaging as messaging`
`ModuleNotFoundError: No module named 'cereal.messaging'`
`(openpilot) yangwoo@corolla:~/work/corolla/openpilot/tools$`

Anyone have the solution for this?
Thanks in advance!

**Comment by rbiasini** [comment]
@yangwoo-kim are you using the latest openpilot version? If so, make sure openpilot tools is on 4f98a868f899602454756eb6e6ffbca84f1ae0ac

**Comment by yangwoo-kim** [comment]
@rbiasini Thank you so much! I've changed the commit to 4f98a86, however, it gives me another issue:

`(openpilot) yangwoo@corolla:~/work/corolla/openpilot/tools$ python carcontrols/joystickd.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
clang++ -g -O3 -fPIC -std=c++11 -Wall -Wextra -Wshadow -Weffc++ -Wstrict-aliasing -Wpedantic -Werror -MMD -I../../selfdrive -I../../phonelibs/zmq/x64/include -I../../phonelibs/yaml-cpp/include   -c -o messaging.o messaging.cc
clang++ -g -O3 -fPIC -std=c++11 -Wall -Wextra -Wshadow -Weffc++ -Wstrict-aliasing -Wpedantic -Werror -MMD -I../../selfdrive -I../../phonelibs/zmq/x64/include -I../../phonelibs/yaml-cpp/include   -c -o impl_zmq.o impl_zmq.cc
[ LINK ] messaging.a
mkdir -p libs; \
	cd libs; \
	ar -x /home/yangwoo/work/corolla/openpilot/phonelibs/zmq/x64/lib/libzmq.a; \
	ar -x /home/yangwoo/work/corolla/openpilot/phonelibs/yaml-cpp/x64/lib/libyaml-cpp.a;
ar rcsD 'messaging.a' messaging.o impl_zmq.o libs/*.o
rm -r libs
python3 messaging_pyx_setup.py build_ext --inplace
Compiling messaging_pyx.pyx because it changed.
[1/1] Cythonizing messaging_pyx.pyx
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'nthreads'
  warnings.warn(msg)
running build_ext
building 'messaging_pyx' extension
creating build
creating build/temp.linux-x86_64-3.7
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/yangwoo/work/corolla/openpilot/selfdrive/messaging -I/usr/local/include/python3.7m -c messaging_pyx.cpp -o build/temp.linux-x86_64-3.7/messaging_pyx.o -std=c++11
g++ -pthread -shared build/temp.linux-x86_64-3.7/messaging_pyx.o /home/yangwoo/work/corolla/openpilot/selfdrive/messaging/messaging.a -o /home/yangwoo/work/corolla/openpilot/selfdrive/messaging/messaging_pyx.so
rm -rf build
rm -f messaging_pyx.cpp
/home/yangwoo/.local/share/virtualenvs/openpilot-C-8G65Jq/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/yangwoo/work/corolla/openpilot/common/clock.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
Aborted (core dumped)
(openpilot) yangwoo@corolla:~/work/corolla/openpilot/tools$ python carcontrols/joystickd.py`

**Comment by yangwoo-kim** [comment]
Hello @rbiasini, Do you have any suggestion?

**Comment by yangwoo-kim** [comment]
Hello @rbiasini, Do you have any suggestion?

**Comment by yangwoo-kim** [comment]
Solved!
