### ISSUE TITLE
nice nui tool! but BASEDIR/cereal/messaging

### ISSUE THREAD

**Issue by ucolchen** [commaai/openpilot-tools#39]
love it! 
- multi-thread loading all the driving-logs
- mouse click instead of key-in s/S/m/M

but, as today, we don't have "messaging" in "cereal", it still in "selfdrive"?
also, I need to setup apache2 to make it localhost for the http.
again, love it! GUI rocks!

thanks,
q

**Comment by rbiasini** [comment]
@ucolchen nui will be usable with openpilot's next release. For now, please refer to the [tagged versions](https://github.com/commaai/openpilot-tools/tags) of openpilot-tools to see which versions are compatible wrt openpilot versions.

**Comment by ucolchen** [comment]
> @ucolchen nui will be usable with openpilot's next release. For now, please refer to the [tagged versions](https://github.com/commaai/openpilot-tools/tags) of openpilot-tools to see which versions are compatible wrt openpilot versions.

thanks for quick response,
just can't wait to use this great GUI, i made link to those missing path, and converted http://data.comma to localhost.
it rocks now! LOVE it!
