### ISSUE TITLE
 safety setting

### ISSUE THREAD

**Issue by yangwoo-kim** [commaai/openpilot-tools#46]
On the following step:

python carcontrols/joystickd.py

-In another terminal:
selfdrive/boardd/tests/boardd_old.py # Make sure the safety setting is hardcoded to ALL_OUTPUT

-In another terminal:
python carcontrols/debug_controls.py

What does "Make sure the safety setting is hardcoded to ALL_OUTPUT" mean and how to set this up?

**Comment by rbiasini** [comment]
that comment should be removed, as it's already the case.

**Comment by yangwoo-kim** [comment]
Thanks!
