### ISSUE TITLE
libmpc1.so cannot be opened - solution inside

### ISSUE THREAD

**Issue by csouers** [commaai/openpilot-tools#6]
**Issue**: Running `python carcontrols/debug_controls.py` yields the following error.

**Error**: `OSError: cannot load library '/home/user/openpilot/selfdrive/controls/lib/longitudinal_mpc/libmpc1.so': /home/user/openpilot/selfdrive/controls/lib/longitudinal_mpc/libmpc1.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/user/openpilot/selfdrive/controls/lib/longitudinal_mpc/libmpc1.so'
`

**Solution**: Run 'make clean' in /selfdrive/controls/lib/longitudinal_mpc/

Credit goes to @wocsor

**Comment by andyh2** [comment]
Fixed in openpilot 0.5.7. https://github.com/commaai/openpilot/blob/9ce3045f139ee29bf0eea5ec59dfe7df9c3d2c51/selfdrive/controls/lib/longitudinal_mpc/libmpc_py.py#L9
